language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      if: type = pull_request
      name: Lint code
      node_js: lts/*
      script:
        - npx eslint .
    - stage: test
      if: type = pull_request
      name: Verify build
      node_js: lts/*
      script:
        - npm run build
    - stage: test
      if: type = pull_request
      name: Run tests
      node_js: lts/*
      script:
        - npm install -g codecov
        - npm test -- --coverage
        - codecov
    - stage: deploy
      if: type = push
      name: Deploy to GitHub Pages
      deploy:
        provider: pages
        local_dir: build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
