language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: Lint code
      node_js: lts/*
      script:
        - npm run lint
    - stage: test
      name: Verify build
      node_js: lts/*
      script:
        - npm run build
    - stage: test
      name: Run tests
      node_js: lts/*
      script:
        - npm install -g codecov
        - npm test -- --coverage
        - codecov
    - stage: deploy
      if: type = push
      name: Deploy to GitHub Pages
      node_js: lts/*
      script:
        - npm run build
      deploy:
        provider: pages
        local_dir: build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        fqdn: salaries.sparksuite.com
