account_id = "f4e4ed8fbf42f6f6b11f42413aa5f27e"
name = "salary-calculator"
type = "webpack"
workers_dev = true

[site]
bucket = "./build"
entry-point = "workers-site"

[env.production]
zone_id = "f32413c72ae75df9ceb8a576c9a1d8db"
route = "salaries.sparksuite.com/*"
