name = "salary-calculator"
account_id = "f4e4ed8fbf42f6f6b11f42413aa5f27e"
route = "salaries.sparksuite.com/*"
main = "workers-site/index.js"
compatibility_date = "2025-01-24"

[site]
bucket = "./build"
