name: Main CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Verify build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn test
      - name: Codecov
        uses: codecov/codecov-action@v3
  deploy:
    name: Deploy to Cloudflare Workers Sites
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: npx wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
